baseURL = 'https://yooooe.github.io/'
languageCode = 'en-us'
title = 'index'

[permalinks]
    blog = "/:filename"

[taxonomies]
    tag = "tags"

[menu]
    [[menu.main]]
        name = "main"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "blogposts"
        url = "/blog/"
        weight = 2
    [[menu.main]]
        name = "tags"
        url = "/tags/"
        weight = 3

[params]
    dateFormat = "02 01 06"
    homeText = ""

[markup.goldmark.renderer]
unsafe= true
